server:
  port: 8081
spring:
  security:
    user:
      name: catalogue_service_user
      password: password
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
      enabled: true
      locations: classpath:db/migration  # Папка с миграциями
      schemas: public                   # Схема БД
      baseline-on-migrate: true         # Создать baseline для существующей БД
      validate-migration-naming: true   # Проверять именование файлов миграций
      connect-retries: 5                # Количество попыток подключения
  jpa:
    show-sql: true

logging:
  level:
    org.flywaydb: DEBUG
    sql: info

