
services:
  postgres:
    image: postgres:16
    container_name: postgres_catalogue
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalogue_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  catalogue_net:
    driver: bridge